{% set name = "dask-mongo" %}
{% set version = "2022.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a50dc71afa5d809e7501f135d1a5b7976f16625d0bbf5f416136ae8c46eef575

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dask
    - distributed
    - pymongo

test:
  imports:
    - dask_mongo
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/coiled/dask-mongo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read and write data to MongoDB with Dask
  doc_url: https://github.com/coiled/dask-mongo/blob/main/README.md
  dev_url: https://github.com/coiled/dask-mongo

extra:
  recipe-maintainers:
    - jrbourbeau
    - ncclementi
